server:
  port: 10001

eureka:
  instance:
    hostname: ip1
  server:
    enableSelfPreservation: false	#可选:关闭自我保护
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:17358687797@ip2:10002/eureka/

#配置认证用户
spring:
  profiles: prod1
  application:
    name: payment-center-eureka
  security:
    user:
      name: admin
      password: 17358687797
