server:
  port: 10001
  
eureka:
  instance:
    hostname: admin:17358687797@localhost
  server:
    enableSelfPreservation: false	#可选:关闭自我保护
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#可选:配置认证用户
spring:
  application:
    name: payment-center-eureka
  security:
    user:
      name: admin
      password: 17358687797
