server:
  port: 42002
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:17358687797@ip1:40001/eureka/,http://admin:17358687797@ip2:40002/eureka/
  instance: 
    preferIpAddress: true # 注册服务时使用ip而非计算机名

management:     #集成消息总线需要
  endpoints:
    web:
      exposure:
        include: bus-refresh

spring:
  rabbitmq:     # 集成消息总线需要
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:        # 集成消息总线需要
    bus:
      enabled: true
      trace:
        enabled: true
  datasource:   # 持久层相关
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/base_demo?characterEncoding=utf8&useInformationSchema=true
    username: root
    password: root
    hikari:
      maxLifetime: 1765000
      maximumPoolSize: 10

mybatis-plus:   # 持久层相关
  type-aliases-package: cn.wine.payment.demo.common.entity
  global-config:
    refresh: true   # 自动刷新Mapper的XML，更改后，无需重启（仅限测试环境使用）
    db-config:
      table-prefix: # 表名前缀

feign:
  hystrix:
    enabled: true   # 打开断路器
